### PR TITLE
Adds support for the picamera2 library

### PR DESCRIPTION
**Pull request by ameneau**
[picamera2](https://github.com/raspberrypi/picamera2) is picamera's successor that will work with the 64bit version of raspbian. There were a few stumbling blocks, but this is working with the current alpha release of picamera2.

### CODE REVIEW

**Comment by ameneau** [comment]
realizing I didn't include a requirements-pi2.txt, I can look at adding that soon. The project I built using this code, I don't have a requirements.txt for yet 😬 Might be a good time to add that, I'll spend some additional time on this soon ✌️

**Comment by ameneau** [comment]
added `requirements-pi2.txt`, but it hasn't been tested yet!

**Comment by ameneau** [comment]
That makes sense to me. I'm using this in a personal project at home, for what I'm doing, it's working great, but I'm not sure how this library will change over time but wanted to make a PR while it was fresh.

your tutorial was super helpful in getting up and running, so thank you for that! I'll hopefully remember to revisit this when picamera2 has a stable release ✌️

**Comment by askpatrickw** [comment]
Hey, all playing around with this today and so far it all worked great. Just a couple of notes. 

1. I installed Click, Flask, Picamer2 from Raspberry Pi Bullseye `sudo apt get install python3-click python3-flask python3-picamera2`. I was on v0.3.9 the latest beta. If you don't want to recommend apt install. I would suggest using the release tags than the commit currently in the PR.
2. I also suggest adding the example to the app.py.

```python
# Raspberry Pi >=4 camera module (requires picamera2 package)
# from camera_pi2 import Camera
```

**Comment by miguelgrinberg** [comment]
Merged, with an update of the requirements file. Thanks!

**Pull request closed without merging**
