### PR TITLE
Added mjpeg streaming Camera() class

### PR DESCRIPTION
**Pull request by terminator14**
Thanks Miguel - your code was a very helpful starting point.
I hope this addition helps someone.

### CODE REVIEW

**Comment by miguelgrinberg** [comment]
Why do you need to pass the camera stream through Flask, in this case? You get the same thing from flask that you can get direct from the camera, so why put Flask in the middle?

**Comment by terminator14** [comment]
One of the things the company I work for offers clients is a way to monitor remote geographic locations. We put a bunch of cameras on site, and let clients connect to, and monitor them. Originally, the way a client would monitor the cameras was a single HTML file we sent them through email. The HTML file was not hosted anywhere - it was stored on the client's computer. It had embeded URLs for the MJPEG streams of the cameras.

There were multiple problems with this approach:

1. The client could see the IP, username, and password that they were accessing the cameras with just by looking at the HTML page source.
2. If we wanted to change the way the page there were seeing looked, we had to update the HTML file on our end, send them the new HTML file, and hope they start using the new file and delete the old file.
3. The WAN link at the remote location with the cameras is a cell modem with very limited monthly bandwidth. If they forgot to close the HTML page and left it running for the night, it would easily go over the monthly limit. We built javascript code into the original HTML page that stopped the camera feed after 10 minutes, but the code was all client-side - they could easily edit the code and disable all limits
4. If the client opened 5 different browser windows, all with that HTML page, the camera WAN link would be streaming the same camera data 5 times
5. Browser support for HTTP authentication is being phased out, presenting many difficulties embedding a link to a stream that has a username and password in the URL. We were basically forced to use iframes, which appear different on different browsers, which was terrible - the HTML page would only work properly on firefox and no other browser

To address all these issues, I used flask to build a website that was actually hosted at our company datacenter. Instead of sending clients an HTML page, they could now punch in the URL we gave them, login with a username and password, and see their camera streams. 

In order, all these problems were addressed (and more):

1. All logic for returning camera feeds was happening server-side. All the client could tell by looking at the source code was that they are requesting cam1, or cam2 from the server - the server figures out which feed to connect them to. They don't know, and don't need to know the username, password or IP of the actual cameras.
2. We can update the website anytime, and it will update it for everybody, just like any other website
3. We put server-side code that stops returning the camera feed if they keep the page open for x minutes. If they refresh the page, it refreshes the timer, but if they leave it idle, it will time out and not waste monthly bandwidth on the cell modem. This limit can be easily overcome since the counter that keeps track of idle timeout is server-side.
4. If the client opens up 5 different browsers looking at the same cameras, or there are multiple clients making a request to the same cameras, we can open a single stream from the cameras to our flask server, and redistribute that feed to 5 different browsers. The cell modem WAN link only takes a hit once no matter how many clients there are.
5. Since the authentication process was now being handled by flask, we no longer had to use iframes on client machines. Our website works with all browsers now - even cell phones.

This was our use-case for flask reading an mjpeg stream.

**Comment by miguelgrinberg** [comment]
So here is why I ask. The goal I had with this project is to use Flask to assemble a mjpeg stream for cameras that return individual jpegs.

In your case, the camera already returns mjpeg, which you break back into individual frames in Python/Flask (which is very slow), to only then have the stream reassembled on its way out to clients.

One potential problem I see is that the frames may not be coming at the correct intervals in the way you are reading the original stream. Consider, for example, a frame that is just 500 bytes long. You are reading in chunks of 1024 bytes, which means that to read 1024 you will be blocked for the time the camera produces 3 frames, and during all that time you will not be sending anything to the client. Then you will have enough data to send two complete frames all in one go, and the remainder of those 1024 frames will stay blocked until you read the next 1024 chars.

It seems in this case all you want is just to proxy the mjpeg stream from the camera, which you can do without parsing the individual frames out of the stream. Just read as much data as available in your input buffer from the camera and dump it all in one chunk to the client.

**Comment by terminator14** [comment]
Hmm. That's a good point. I might have to try that.

**Comment by terminator14** [comment]
It's kind of late here in Canada, so I'm not thinking straight at the moment, but if I understand you correctly, you're saying that when the generator yields something, it doesn't necessarily need to be a single frame of a jpeg - it can be a much larger set of data that includes several jpegs, and even partially constructed jpegs, as long as the next time it yields something, the rest of that partial jpeg data is sent to the browser?

I was under the impression that when you yield something, it needed to be a single jpeg.

**Comment by miguelgrinberg** [comment]
> In our case, all frames are definitely much bigger than 1024 bytes
> I would guess that most cameras, at any usable resolution would produce images bigger than 1024 bytes

It's still a problem. If your frame is 10241 bytes, you will need to do 10 reads of 1024, then will be blocked until the camera generates the next frame to get the last byte and you can read the last byte of your current frame.

The correct implementation for something like this is to let the mjpeg source dictate what the chunk sizes are, and you just read exactly what the camera sends to guarantee that you are never blocked.

> In our case, low framerate isn't a big deal

This isn't just a problem of slow frame rate, but of an uneven frame rate, which in my opinion is worse.

The expected way a mjpeg should stream is that a chunk of exactly one frame is delivered at the interval that corresponds to the camera frame rate. Since each jpeg is likely going to be a different size, the chunks in the stream are all going to be different sizes as well.

The main problem with your implementation is that your reads are blocking. If the camera sent 10241 bytes in one chunk, and you read 10240 and are still missing the last byte, you should have the logic that tells you that you need to read one byte, instead of reading 1024 and then extracting the byte that you need. After you read the 10240 bytes your input buffer is going to have just one byte, so reading 1024 will cause the read to block until the next frame arrives.

**Comment by terminator14** [comment]
The new version seems to work a lot better. It only reads as much data as it needs to, and is a lot smoother - frames do not appear uneven.

The only thing I'm not entirely sure about is the byte count. I know that for my mjpeg stream, the content length value starts at exactly the 63rd byte, and ends when I see '\r\n\r\n'. The first '\r' gets read by `content_length += self.stream.read(1)`, so as soon as I see it, I ignore it and ignore the next 3 bytes as well. I'm not entirely sure if this is always the case for all mjpeg streams. Apparently, there's no standard for mjpeg: http://stackoverflow.com/a/885229/6423456. For the stream I'm working with, this code appears to work great.

It's late again - I removed the part of my code that did extended error checking to see if a stream looked like a proper mjpeg stream, but the error image and variables dealing with it still remain - I'll probably clean that up tomorrow.

Does it look better?

**Comment by terminator14** [comment]
If the byte count won't always be the same, maybe it would be a better idea to read the stream one byte at a time until I come across the string 'Content Length', and then instead of skipping 4 bytes after reading the actual content length, I just keep reading one byte at a time until I get to '\xff\xd8'?

Or would the byte count be good enough?

And do you know if there's a performance hit when reading data one byte at a time like this? I'm only doing it for a few bytes at a time.

**Comment by miguelgrinberg** [comment]
What I don't understand is why do you need to process the mjpeg stream twice. The camera is already doing the streaming, so all you need to do in your Flask server is read from the camera, and write to the client. This application is not appropriate for your use case.

All the work you are doing in flask to segment the stream by parsing headers is all wasted effort, since the camera is already giving you a perfectly valid stream that you can send to your clients.

You need something simpler that just reads on one end and writes on the other, without doing all the mjpeg formatting and without doing any parsing. You can probably strip all that from the server.

Regarding your question, reading byte by byte is going to have a severe performance penalty. Python is a slow language, so all the assembling that will need to take place when you read byte by byte is going to have a severe impact.

**Comment by terminator14** [comment]
I needed a way to read an mjpeg stream, and deal with it in flask. I started out having no clue how to even approach this problem. Most HowTos out there deal with opencv, which looked fairly heavy for my simple task. Your tutorial is one of the few resources online that I could find dealing specifically with flask and mjpeg, and in a way that was simple and lightweight. After minimal effort, I was able to modify your basic example to do what I needed, and although the speed wasn't great, it wasn't terrible for what I was trying to accomplish. I knew that there was probably a more efficient way to do this, but my experience with streams of bytes is fairly limited, so I was just happy to see it work.

Now that you have pointed out that for my application, there's a more efficient way of doing things, and that your code was meant to string images together into an mjpeg stream, rather than process an existing mjpeg stream, I'll have to look into how to do that. I need an efficient way to read an mjpeg stream, and redistribute it to multiple clients at the same time.

**Comment by terminator14** [comment]
Since reading an mjpeg stream is not what your project is about, I'll cancel my pull request in a bit.
Thanks for answering my questions, and pointing me in the right direction.

Ultimately, I'll probably end up modifying my code to get away from your approach, as you suggested, but it was still an interesting learning experience - thanks for that.

**Pull request closed without merging**
